# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c407e30744603c9172b929d7d8662b5731d4f48bde9fb5fa5a4a5ee28ee00d6c58e3aa067f8a111d709e77e0b35a46423a4409f84f27bc9776b92672c9f44cb7

test:
  secret_key_base: 4086bf2bd8ca30f6a7f4c0133ea4ff79d88cef6a83dcccc151a413826ec45bb54f423e4a113a323ef47a98e798cb0531aa876d42d360130326b3b1a1599b20fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
